name: CI Pipeline

on:
  push:  # push時に実行
    paths:
      - "**"  # すべてのファイルの変更が対象
  pull_request:  # プルリクエスト作成・更新時に実行
    paths:
      - "**"

jobs:
  build:
    name: Code Checks  # ジョブ名
    runs-on: ubuntu-latest  # 最新の Ubuntu 仮想環境上でジョブを実行

    steps:
      - name: Checkout code  # リポジトリのコードを取得
        uses: actions/checkout@v4

      - name: Set up Python  # Python 3.13 をセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry  # Poetry（依存管理ツール）をインストール
        uses: snok/install-poetry@v1
        with:
          poetry-version: 2.1.3

      - name: Install dependencies  # poetry.lock / pyproject.toml に従って依存関係をインストール
        run: poetry install

      - name: Run Ruff linter  # Ruff による Lint チェック（コード品質・構文チェック）
        run: poetry run ruff check .

      - name: Run tests with pytest  # pytest実行
        run: poetry run pytest
